# country abbreviaiton data
Africa
AI
AL
AN
BA
BE
BT
BF
BR
BU
BH
CR
CI
CV
CA
DH
DC
EG
ER
ET
GB
GA
GH
GC
GU
HO
IC
KY
LE
LI
LB
MD
MW
ML
MN
MU
MA
MB
ME
MR
MZ
NM
NG
NI
PY
CH
RD
RE
RG
RS
SY
RC
RI
RW
SE
SN
SL
SO
SA
SS
SU
SH
SW
TA
TO
TN
UG
UC
--
YA
ZA
ZM
ZI
ZU



Asia
AH
AF
AK
AL
AR
AM
AY
AB
AZ
BY
BI
BA
BE
BH
BO
BN
BR
BU
CM
CH
CU
DK
EL
EV
GE
HA
HE
HI
HT
IN
ID
IR
IQ
IS
IT
JA
JW
JO
KA
KZ
KT
KR
KU
KY
LA
LE
MA
MS
ME
MY
MO
MG
MM
NA
NG
NE
NS
OM
OS
OT
PK
PE
PH
PO
QA
RK
ML
SA
SB
SC
SE
SI
SR
SU
SY
TW
TJ
TS
TM
TH
TB
TL
TN
TU
TK
TV
UL
UA
--
UR
UZ
VT
YK
YE



Europe
AL
AN
AS
BS
BA
BL
BE
BH
BU
BZ
CC
CE
CH
CR
CY
CZ
CP
DE
EN
ES
FI
FL
FR
GA
GU
GE
GB
GR
GY
HU
IC
IR
IT
KL
KA
KO
KS
LP
LA
LV
LE
LI
LU
MA
ML
MR
MD
MN
MO
NS
NO
OS
OG
PO
PG
RM
RO
RU
SM
SD
SC
SY
SE
SL
SV
SI
SO
SP
SW
SZ
TT
TU
DU
UD
UK
--
WA
YU


North America
AC
AU
AL
AM
AN
AT
AR
AB
AZ
BB
BC
BL
BO
CA
CG
CE
CY
CH
CI
CO
CU
BA
CR
CB
DA
DO
DR
ES
EK
GL
GR
HA
HO
IN
IR
JM
KL
KW
LA
MA
ME
NV
OH
OJ
OS
PW
PE
PP
PO
PU
PR
SK
SL
SV
SA
SE
SH
SX
TL
US
--
VI
YU
ZU



Oceania
AU
CI
CO
FJ
GM
HA
KI
MA
MI
ME
MC
NA
NB
NC
GU
NZ
NI
PN
PO
PA
SA
SI
SO
TO
TU
TV
--
VA
YO


South America
AC
AR
BE
BO
RR
BR
CH
CI
CO
CR
EC
ES
FI
FG
GU
GY
HO
IN
JM
MY
NA
NI
PM
PA
PE
SU
TT
--
UR
VE



