---
output:
  word_document: default
  pdf_document: default
  html_document: default
---
<table><tbody><tr><td><p>2-Letter</p></td><td><p>3-Letter</p></td><td><p>Country Name</p></td></tr><tr><td><p>DZ</p></td><td><p>DZA</p></td><td><p>Algeria</p></td></tr><tr><td><p>AO</p></td><td><p>AGO</p></td><td><p>Angola</p></td></tr><tr><td><p>BJ</p></td><td><p>BEN</p></td><td><p>Benin</p></td></tr><tr><td><p>BW</p></td><td><p>BWA</p></td><td><p>Botswana</p></td></tr><tr><td><p>BF</p></td><td><p>BFA</p></td><td><p>Burkina Faso</p></td></tr><tr><td><p>BI</p></td><td><p>BDI</p></td><td><p>Burundi</p></td></tr><tr><td><p>CM</p></td><td><p>CMR</p></td><td><p>Cameroon</p></td></tr><tr><td><p>CV</p></td><td><p>CPV</p></td><td><p>Cape Verde</p></td></tr><tr><td><p>CF</p></td><td><p>CAF</p></td><td><p>Central African Republic</p></td></tr><tr><td><p>TD</p></td><td><p>TCD</p></td><td><p>Chad</p></td></tr><tr><td><p>KM</p></td><td><p>COM</p></td><td><p>Comoros</p></td></tr><tr><td><p>CG</p></td><td><p>COG</p></td><td><p>Congo</p></td></tr><tr><td><p>CD</p></td><td><p>COD</p></td><td><p>Congo, Democratic Republic of</p></td></tr><tr><td><p>CI</p></td><td><p>CIV</p></td><td><p>Côte d'Ivoire</p></td></tr><tr><td><p>DJ</p></td><td><p>DJI</p></td><td><p>Djibouti</p></td></tr><tr><td><p>EG</p></td><td><p>EGY</p></td><td><p>Egypt</p></td></tr><tr><td><p>GQ</p></td><td><p>GNQ</p></td><td><p>Equatorial Guinea</p></td></tr><tr><td><p>ER</p></td><td><p>ERI</p></td><td><p>Eritrea</p></td></tr><tr><td><p>ET</p></td><td><p>ETH</p></td><td><p>Ethiopia</p></td></tr><tr><td><p>GA</p></td><td><p>GAB</p></td><td><p>Gabon</p></td></tr><tr><td><p>GM</p></td><td><p>GMB</p></td><td><p>Gambia</p></td></tr><tr><td><p>GH</p></td><td><p>GHA</p></td><td><p>Ghana</p></td></tr><tr><td><p>GN</p></td><td><p>GIN</p></td><td><p>Guinea</p></td></tr><tr><td><p>GW</p></td><td><p>GNB</p></td><td><p>Guinea-Bissau</p></td></tr><tr><td><p>KE</p></td><td><p>KEN</p></td><td><p>Kenya</p></td></tr><tr><td><p>LS</p></td><td><p>LSO</p></td><td><p>Lesotho</p></td></tr><tr><td><p>LR</p></td><td><p>LBR</p></td><td><p>Liberia</p></td></tr><tr><td><p>LY</p></td><td><p>LBY</p></td><td><p>Libyan Arab Jamahiriya</p></td></tr><tr><td><p>MG</p></td><td><p>MDG</p></td><td><p>Madagascar</p></td></tr><tr><td><p>MW</p></td><td><p>MWI</p></td><td><p>Malawi</p></td></tr><tr><td><p>ML</p></td><td><p>MLI</p></td><td><p>Mali</p></td></tr><tr><td><p>MR</p></td><td><p>MRT</p></td><td><p>Mauritania</p></td></tr><tr><td><p>MU</p></td><td><p>MUS</p></td><td><p>Mauritius</p></td></tr><tr><td><p>YT</p></td><td><p>MYT</p></td><td><p>Mayotte</p></td></tr><tr><td><p>MA</p></td><td><p>MAR</p></td><td><p>Morocco</p></td></tr><tr><td><p>MZ</p></td><td><p>MOZ</p></td><td><p>Mozambique</p></td></tr><tr><td><p>NA</p></td><td><p>NAM</p></td><td><p>Namibia</p></td></tr><tr><td><p>NE</p></td><td><p>NER</p></td><td><p>Niger</p></td></tr><tr><td><p>NG</p></td><td><p>NGA</p></td><td><p>Nigeria</p></td></tr><tr><td><p>RE</p></td><td><p>REU</p></td><td><p>Reunion</p></td></tr><tr><td><p>RW</p></td><td><p>RWA</p></td><td><p>Rwanda</p></td></tr><tr><td><p>SH</p></td><td><p>SHN</p></td><td><p>Saint Helena</p></td></tr><tr><td><p>ST</p></td><td><p>STP</p></td><td><p>Sao Tome and Principe</p></td></tr><tr><td><p>SN</p></td><td><p>SEN</p></td><td><p>Senegal</p></td></tr><tr><td><p>SC</p></td><td><p>SYC</p></td><td><p>Seychelles</p></td></tr><tr><td><p>SL</p></td><td><p>SLE</p></td><td><p>Sierra Leone</p></td></tr><tr><td><p>SO</p></td><td><p>SOM</p></td><td><p>Somalia</p></td></tr><tr><td><p>ZA</p></td><td><p>ZAF</p></td><td><p>South Africa</p></td></tr><tr><td><p>SS</p></td><td><p>SSD</p></td><td><p>South Sudan</p></td></tr><tr><td><p>SD</p></td><td><p>SDN</p></td><td><p>Sudan</p></td></tr><tr><td><p>SZ</p></td><td><p>SWZ</p></td><td><p>Eswatini, formerly known as Swaziland</p></td></tr><tr><td><p>TZ</p></td><td><p>TZA</p></td><td><p>Tanzania</p></td></tr><tr><td><p>TG</p></td><td><p>TGO</p></td><td><p>Togo</p></td></tr><tr><td><p>TN</p></td><td><p>TUN</p></td><td><p>Tunisia</p></td></tr><tr><td><p>UG</p></td><td><p>UGA</p></td><td><p>Uganda</p></td></tr><tr><td><p>EH</p></td><td><p>ESH</p></td><td><p>Western Sahara</p></td></tr><tr><td><p>ZM</p></td><td><p>ZMB</p></td><td><p>Zambia</p></td></tr><tr><td><p>ZW</p></td><td><p>ZWE</p></td><td><p>Zimbabwe</p></td></tr></tbody></table>